---
- name: Autostart | VM Inventory Mapper
  import_tasks: mapper.yml

- name: Autostart | What VMs to Adjust
  block:
    - name: Autostart | Getting a list of vms
      community.libvirt.virt:
        command: list_vms
      register: vms_list
    - name: Autostart | Vms being adjusted
      debug:
        var: vms_list.list_vms
        verbosity: 1
    - name: Autostart | Filter VM List
      set_fact:
        vms_to_autostart: "{{ (vms_to_autostart | default([])) + [item] }}"
      loop: "{{ vms_list.list_vms }}"
      when: item in cluster_vm_names
  become: true

- name: Autostart | "setting {{ vms_to_autostart }} to autostart"
  debug:
    var: vms_to_autostart
    verbosity: 1

- name: Autostart | "Setting {{ item }} to autostart"
  community.libvirt.virt:
    command: autostart
    name: "{{ item }}"
  loop: "{{ vms_to_restart | default([]) }}"
  ignore_errors: yes
  become: true
