---
- name: Setup host environment
  become: true
  block:
    - name: "Install packages"
      import_tasks: install.yml

    - name: Start libvirtd
      service:
        name: libvirtd
        state: started

- name: Prepare Network
  import_tasks: prepare_network.yml

- name: Prepare Storage Pool
  import_tasks: prepare_storage_pool.yml

- name: Prepare VMS
  import_tasks: provision_vms.yml
