---
- name: Create inventory host to vm name mapper
  set_fact:
    cluster_vm_names: "{{ (cluster_vm_names | default([])) + [item.startswith(cluster_name) | ternary(item, (cluster_name + '_' + item))] }}"
  loop: "{{ groups['nodes'] }}"
  when: hostvars[item]['vendor'] | lower == 'kvm'

# - debug: # noqa unnamed-task
#     var: vm_to_inventory_mapper
#     verbosity: 1
