---
- name: Set default for kvm_nodes
  set_fact:
    all_kvm_nodes: {}

- name: Set kvm facts
  include_tasks: process_node_facts.yml
  loop: "{{ groups['nodes'] }}"
  loop_control:
    loop_var: kvm_node_hostname
  when: hostvars[kvm_node_hostname]['vendor'] | lower == 'kvm'

- name: Distribute kvm_nodes for vm_host to that host
  set_fact:
    kvm_nodes: "{{ all_kvm_nodes[item] | default([]) }}"
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups['vm_hosts'] | default([]) }}"
