### Process kvm nodes
vm_spec_defaults:
  master:
    memory: 16384
    vcpu: 6
    disk_size: 30
  worker:
    memory: 30000
    vcpu: 8
    disk_size: 50

vm_group_params:
  master:
    memory: "{{ vm_spec_master_memory | default(vm_spec_defaults.master.memory) }}"
    vcpu: "{{ vm_spec_master_vcpu | default(vm_spec_defaults.master.vcpu) }}"
    disk_size: "{{ vm_spec_master_disk_size | default(vm_spec_defaults.master.disk_size) }}"
  worker:
    memory: "{{ vm_spec_worker_memory | default(vm_spec_defaults.worker.memory) }}"
    vcpu: "{{ vm_spec_worker_vcpu | default(vm_spec_defaults.worker.vcpu) }}"
    disk_size: "{{ vm_spec_worker_disk_size | default(vm_spec_defaults.worker.disk_size) }}"

### Create_vms
network_name: "net-{{ cluster_name }}"
vm_create_scripts_dir: /home/redhat/vm_create_scripts/

virt_packages:
  - python3
  - libvirt
  - virt-install
  - qemu-kvm
  - virt-manager
  - python3-pip
  - python3-lxml
  - python3-libvirt

images_dir: /var/lib/libvirt/images/


### Destroy_vms
virt_packages:
  - python3
  - libvirt
  - virt-install
  - qemu-kvm
  - virt-manager
  - python3-pip
  - python3-lxml
  - python3-libvirt

images_dir: /var/lib/libvirt/images/
vm_create_scripts_dir: /home/redhat/vm_create_scripts/

vm_bridge_name: "{{ cluster_name }}-br"
network_name: "net-{{ cluster_name }}"

### setup_vm_host_network
vm_bridge_ip: "{{ machine_network_cidr | ipaddr('next_usable') }}"
vm_bridge_prefix: "{{ machine_network_cidr | ipaddr('prefix') }}"
vm_bridge_name: "{{ cluster_name }}-br"
vm_bridge_port_name: "{{ vm_bridge_interface }}"
vm_vlan_name: "{{ cluster_name }}.{{ vm_vlan_tag }}"
vm_nmstate_config_path: "/tmp/{{ cluster_name }}_nmstate.yml"
